import Head from 'next/head';
import styles from '@o2/styles/Home.module.css';
import Link from 'next/link';
import { List } from 'reactstrap';
import { useUserContext } from '@o2/hooks/useUserContext';

const Home = () => {
  const { username } = useUserContext();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <List>
          {!username && (
            <li>
              <Link href="/login">Login</Link>
            </li>
          )}
          {username && (
            <li>
              <Link href="/posts">Posts</Link>
            </li>
          )}
        </List>
      </main>
    </>
  );
};

export default Home;
